### ISSUE TITLE
[PE-D][Tester B] Lack of screenshots to explain the features in the UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-1/tp#135]
![image.png](https://raw.githubusercontent.com/Rishit02/ped/main/files/4d12eb9c-67a9-4dc6-a98b-0fe653cf8c6c.png)

Expected there to be more screenshots of the actual application in action. Might be possible to add a few more screenshots explaining how to use the `add` function or the `list` function and the common error messages that can be encountered.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Rishit02/ped#10

**Comment by ejnan** [comment]
Would this be necessary? TBD
