### ISSUE TITLE
[PE-D][Tester B] Use of sliding window in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-1/tp#150]
![image.png](https://raw.githubusercontent.com/Rishit02/ped/main/files/ddaa5e56-e434-4e08-920f-69a2e02bb9ea.png)

It might be easier to add these available commands in a normal text box, as the pdf format limits the user from sliding to see the full command.

As a result of this the add command is blocked.

![image.png](https://raw.githubusercontent.com/Rishit02/ped/main/files/662c81b6-d290-495b-9b2f-78366ed2dd30.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Rishit02/ped#17

**Comment by ejnan** [comment]
Not sure how to implement this as the pdf is just created straight from the website

**Comment by ejnan** [comment]
add a new line for long codes
